version: "3"

vars:
  CC_FLAGS: -std=c23 -Wall -Wextra -Wpedantic
  BUILD_DIR: build
  EXECUTABLE: ngc

tasks:
  default:
    cmd: task -a

  clean:
    cmd: rm -rf {{.BUILD_DIR}}

  build:
    cmds:
      - test -d {{.BUILD_DIR}} || mkdir {{.BUILD_DIR}}
      - gcc {{.CC_FLAGS}} -o {{.BUILD_DIR}}/{{.EXECUTABLE}} src/main.c

  execute:
    deps:
      - build
    cmd: ./{{.BUILD_DIR}}/{{.EXECUTABLE}}
