version: "3"

vars:
  BUILD_DIR: bin
  EXECUTABLE: ngc

tasks:
  default:
    cmd: task -a

  clean:
    cmd: rm -rf {{.BUILD_DIR}}

  build:
    cmds:
      - test -d {{.BUILD_DIR}} || mkdir {{.BUILD_DIR}}
      - gcc -Wall -o {{.BUILD_DIR}}/{{.EXECUTABLE}} src/main.c

  execute:
    deps:
      - build
    cmd: ./{{.BUILD_DIR}}/{{.EXECUTABLE}}
